# Generated by Django 4.2 on 2023-04-11 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="User",),
    ]
