# Generated by Django 4.2 on 2023-04-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="usertype",
            field=models.CharField(default="user", max_length=100),
        ),
    ]
