# Generated by Django 4.2 on 2023-04-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_user_usertype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="usertype",
            field=models.BooleanField(default="user"),
        ),
    ]
