# Generated by Django 4.2 on 2023-05-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="product_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="cart", name="product_qty", field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="cart", name="total", field=models.IntegerField(null=True),
        ),
    ]
