# Generated by Django 4.2 on 2023-05-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0012_cart_product_name_cart_product_qty_cart_total"),
    ]

    operations = [
        migrations.RemoveField(model_name="cart", name="product_name",),
        migrations.AddField(
            model_name="cart",
            name="product_price",
            field=models.IntegerField(null=True),
        ),
    ]
