# Generated by Django 4.2 on 2023-05-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0013_remove_cart_product_name_cart_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="product_qty",
            field=models.IntegerField(default=1, null=True),
        ),
    ]
