# Generated by Django 4.2 on 2023-05-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0014_alter_cart_product_qty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart", name="product_price", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="cart", name="product_qty", field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="cart", name="total", field=models.IntegerField(),
        ),
    ]
