# Generated by Django 4.2 on 2023-05-16 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0017_transaction"),
    ]

    operations = [
        migrations.RemoveField(model_name="transaction", name="product",),
    ]
